# -*- coding: utf-8 -*-
"""Prompts.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aroVYgKSgqvUnYfGacGoZbzvsYJ_L4g5

SUMMARY_PROMPT
"""

SUMMARY_PROMPT = """You are an assistant to a microfinance loan officer. Give a factual and neutral summary of the loan application.
Do not invent any details.
Keep the summary between 3 and 4 sentences"""

"""EXTRACT_PROMPT"""

EXTRACT_PROMPT='''return ONLY a JSON object with EXACTLY these keys:
applicant_name (string), amount_ghs (number), purpose (string),
monthly_profit_ghs (number or null), has_collateral_or_guarantor (boolean),
repayment_months (number or null)
If a field is not stated in the letter, use null. Do not guess.
example:
letter: My name is Wilson. I need about 10000 Ghana cedis to start a business and i expect to make 20000 Ghana cedis in profit every month. I will give my phone as a collateral and i will  pay back in a year.


JSON:{
    "applicant_name": "Wilson",
    "amount_ghs": 10000,
    "purpose": "start a business",
    "monthly_profit_ghs": 20000,
    "has_collateral_or_guarantor": true,
    "repayment_months": 12}'''

"""BRIEF_OUTPUT"""

BRIEF_PROMPT='''
With the loan application letter and the extracted JSON, you must output:
1. Strengths (bullet points, grounded in the letter)
2. Risks / red flags (bullet points)
3. Missing information the officer should request
4. Suggested next step (e.g. "invite for interview", "request documents",
   "flag for senior review") — NOT "approve" or "reject".
final decisions are made by humans so do not make any final decision
'''